### ISSUE TITLE
The labels of the confusion matrix seem to be swapped

### ISSUE THREAD

**Issue by Kai-Karren** [Demfier/multimodal-speech-emotion-recognition#17]
Hi, I think you have swapped the x and y label in the  plot_confusion_matrix method in the notebooks.

It confused me, so I thought i should ask you to check that.
However that is only a small thing in this excellent repo. 

Regards,
Kai Karren

**Comment by Demfier** [comment]
Hi @Kai-Karren,

The axis-labels seem okay to me. The y-axis represents the true label and the x-axis represents the predicted labels. For a perfect classifier, the confusion matrix should be a diagonal matrix. For the rest, let's consider the following confusion matrix.

![cm](https://user-images.githubusercontent.com/12595718/69767367-e32ec780-1149-11ea-88be-4159c42b770b.png)

Let's see what's happening for the `ang` class. So there are 222 ang examples in total, and understandably, there are misclassifications. In this case, our model predicted 83 of them as angry, 11 as happy, 93 as sad, 13 as fear, 4 as surprised and 18 as neutral. So the corresponding row for `ang` in the matrix becomes `[83, 11, 93, 13, 4, 18]` Extending this to all the classes, we would get the confusion matrix we have right now.

I understand that the confusion might've arisen (which is only natural, given the name "confusion"-matrix :stuck_out_tongue_winking_eye: ) due to the discrepancy in axes-conventions used by scikit-learn and what we use in-theory. You can look at this [tutorial](https://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html) and see how they've labeled the axes.

In any case, thank you very much for bringing this issue up. Let me know if you spot something else.

Best,
Gaurav.

**Comment by Kai-Karren** [comment]
Hi @Demfier 

thanks for this detailed explanation. Then the labels are correct. I learned it with the labels flipped. Good to to know that scikit-learn uses an other convention.

If I find something else, I will ask again :smile: 

Regards,
Kai
